# Generated by Django 5.2.1 on 2025-08-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0021_rename_user_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
