# Generated by Django 5.2.1 on 2025-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_customuser_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('paid_user', 'Paid User'), ('admin', 'Admin'), ('support', 'Support Member')], default='guest', max_length=20, null=True),
        ),
    ]
